import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { table } from 'console'
import TableComponent from '@/components/table'

const inter = Inter({ subsets: ['latin'] })

interface ITables {
  id: number
  name: string
  status: boolean
}

export default function Home() {

let tables: ITables[]= [
  {id: 1, name: "table1", status: true},
  {id: 2, name: "table2", status: false},
  {id: 3, name: "table3", status: true}
]


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <h1>hello</h1>
      <div>
        {
          tables.map((table) => {
            return (
              <TableComponent name={table.name} status={table.status}></TableComponent>
            )
          }
          )
        }
      </div>
    </main>
    </>
  )
}
